language: go

go: 
  - 1.5
  
install: 
  - go get github.com/bmizerany/assert
  - go get github.com/ddollar/dist
  - go get github.com/devangel/config
  - go get github.com/ViViDboarder/gotifier
  - go get github.com/bgentry/speakeasy
  - go get bitbucket.org/pkg/inflect
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
